//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:21:15 AM EDT 
//


package org.x3d.model;

/*
 * _
 * The Open Semantic Network Analysis Platform (OSNAP)
 * _
 * Copyright (C) 2012 - 2014 Visionarium at Virginia Tech
 * _
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * _
 */

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}SceneGraphStructureNodeType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{}ChildContentModelCore"/>
 *         &lt;group ref="{}GroupingNodeChildContentModel"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
//    "metadataObjects",
    "childObjects"
})
@XmlRootElement(name = "Scene")
public class Scene
    extends SceneGraphStructureNode
{
    /*
    @XmlElements({
        @XmlElement(name = "MetadataDouble", type = MetadataDouble.class),
        @XmlElement(name = "MetadataFloat", type = MetadataFloat.class),
        @XmlElement(name = "MetadataInteger", type = MetadataInteger.class),
        @XmlElement(name = "MetadataSet", type = MetadataSet.class),
        @XmlElement(name = "MetadataString", type = MetadataString.class)
    })
    protected ArrayList<X3DMetadataObject> metadataObjects;
*/
    @XmlElements({
        @XmlElement(name = "Appearance", type = Appearance.class),
        @XmlElement(name = "Background", type = Background.class),
//        @XmlElement(name = "ColorInterpolator", type = ColorInterpolator.class),
//        @XmlElement(name = "CoordinateInterpolator", type = CoordinateInterpolator.class),
        @XmlElement(name = "DirectionalLight", type = DirectionalLight.class),
        @XmlElement(name = "Group", type = Group.class),
        @XmlElement(name = "NavigationInfo", type = NavigationInfo.class),
//        @XmlElement(name = "NormalInterpolator", type = NormalInterpolator.class),
//        @XmlElement(name = "OrientationInterpolator", type = OrientationInterpolator.class),
//        @XmlElement(name = "PositionInterpolator", type = PositionInterpolator.class),
//        @XmlElement(name = "ScalarInterpolator", type = ScalarInterpolator.class),
        @XmlElement(name = "Shape", type = Shape.class),
//        @XmlElement(name = "TimeSensor", type = TimeSensor.class),
        @XmlElement(name = "Transform", type = Transform.class),
        @XmlElement(name = "Viewpoint", type = Viewpoint.class),
        @XmlElement(name = "WorldInfo", type = WorldInfo.class),
        @XmlElement(name = "Anchor", type = Anchor.class),
        @XmlElement(name = "BooleanFilter", type = BooleanFilter.class),
//        @XmlElement(name = "BooleanSequencer", type = BooleanSequencer.class),
        @XmlElement(name = "BooleanToggle", type = BooleanToggle.class),
        @XmlElement(name = "BooleanTrigger", type = BooleanTrigger.class),
//        @XmlElement(name = "CylinderSensor", type = CylinderSensor.class),
//        @XmlElement(name = "Inline", type = Inline.class),
//        @XmlElement(name = "IntegerSequencer", type = IntegerSequencer.class),
        @XmlElement(name = "IntegerTrigger", type = IntegerTrigger.class),
        @XmlElement(name = "KeySensor", type = KeySensor.class),
//        @XmlElement(name = "PlaneSensor", type = PlaneSensor.class),
        @XmlElement(name = "PointLight", type = PointLight.class),
//        @XmlElement(name = "ProximitySensor", type = ProximitySensor.class),
//        @XmlElement(name = "SphereSensor", type = SphereSensor.class),
        @XmlElement(name = "SpotLight", type = SpotLight.class),
        @XmlElement(name = "StringSensor", type = StringSensor.class),
        @XmlElement(name = "Switch", type = Switch.class),
//        @XmlElement(name = "TimeTrigger", type = TimeTrigger.class),
        @XmlElement(name = "TouchSensor", type = TouchSensor.class),
//        @XmlElement(name = "AudioClip", type = AudioClip.class),
        @XmlElement(name = "Billboard", type = Billboard.class),
//        @XmlElement(name = "Collision", type = Collision.class),
//        @XmlElement(name = "Fog", type = Fog.class),
//        @XmlElement(name = "LoadSensor", type = LoadSensor.class),
//        @XmlElement(name = "LocalFog", type = LocalFog.class),
        @XmlElement(name = "LOD", type = LOD.class),
        @XmlElement(name = "Script", type = Script.class),
//        @XmlElement(name = "Sound", type = Sound.class),
//        @XmlElement(name = "VisibilitySensor", type = VisibilitySensor.class),
//        @XmlElement(name = "CoordinateInterpolator2D", type = CoordinateInterpolator2D.class),
//        @XmlElement(name = "PositionInterpolator2D", type = PositionInterpolator2D.class),
        @XmlElement(name = "StaticGroup", type = StaticGroup.class),
//        @XmlElement(name = "CADAssembly", type = CADAssembly.class),
//        @XmlElement(name = "CADLayer", type = CADLayer.class),
        @XmlElement(name = "OrthoViewpoint", type = OrthoViewpoint.class),
//        @XmlElement(name = "ViewpointGroup", type = ViewpointGroup.class),
//        @XmlElement(name = "ColorDamper", type = ColorDamper.class),
//        @XmlElement(name = "CoordinateDamper", type = CoordinateDamper.class),
//        @XmlElement(name = "OrientationChaser", type = OrientationChaser.class),
//        @XmlElement(name = "OrientationDamper", type = OrientationDamper.class),
//        @XmlElement(name = "PositionChaser", type = PositionChaser.class),
//        @XmlElement(name = "PositionChaser2D", type = PositionChaser2D.class),
//        @XmlElement(name = "PositionDamper", type = PositionDamper.class),
//        @XmlElement(name = "PositionDamper2D", type = PositionDamper2D.class),
//        @XmlElement(name = "ScalarChaser", type = ScalarChaser.class),
//        @XmlElement(name = "TexCoordDamper2D", type = TexCoordDamper2D.class),
//        @XmlElement(name = "TextureBackground", type = TextureBackground.class),
//        @XmlElement(name = "CollidableShape", type = CollidableShape.class),
//        @XmlElement(name = "CollisionSensor", type = CollisionSensor.class),
//        @XmlElement(name = "RigidBodyCollection", type = RigidBodyCollection.class),
//        @XmlElement(name = "EspduTransform", type = EspduTransform.class),
//        @XmlElement(name = "ReceiverPdu", type = ReceiverPdu.class),
//        @XmlElement(name = "SignalPdu", type = SignalPdu.class),
//        @XmlElement(name = "TransmitterPdu", type = TransmitterPdu.class),
//        @XmlElement(name = "DISEntityManager", type = DISEntityManager.class),
//        @XmlElement(name = "GeoLocation", type = GeoLocation.class),
//        @XmlElement(name = "GeoLOD", type = GeoLOD.class),
//        @XmlElement(name = "GeoMetadata", type = GeoMetadata.class),
//        @XmlElement(name = "GeoOrigin", type = GeoOrigin.class),
//        @XmlElement(name = "GeoPositionInterpolator", type = GeoPositionInterpolator.class),
//        @XmlElement(name = "GeoProximitySensor", type = GeoProximitySensor.class),
//        @XmlElement(name = "GeoTouchSensor", type = GeoTouchSensor.class),
//        @XmlElement(name = "GeoViewpoint", type = GeoViewpoint.class),
//        @XmlElement(name = "GeoTransform", type = GeoTransform.class),
//        @XmlElement(name = "HAnimHumanoid", type = HAnimHumanoid.class),
//        @XmlElement(name = "HAnimJoint", type = HAnimJoint.class),
//        @XmlElement(name = "HAnimSegment", type = HAnimSegment.class),
//        @XmlElement(name = "HAnimSite", type = HAnimSite.class),
//        @XmlElement(name = "NurbsOrientationInterpolator", type = NurbsOrientationInterpolator.class),
//        @XmlElement(name = "NurbsPositionInterpolator", type = NurbsPositionInterpolator.class),
//        @XmlElement(name = "NurbsSurfaceInterpolator", type = NurbsSurfaceInterpolator.class),
//        @XmlElement(name = "NurbsSet", type = NurbsSet.class),
//        @XmlElement(name = "ProtoInstance", type = ProtoInstance.class),
        @XmlElement(name = "ROUTE", type = ROUTE.class)//,
//        @XmlElement(name = "ExternProtoDeclare", type = ExternProtoDeclare.class),
//        @XmlElement(name = "ProtoDeclare", type = ProtoDeclare.class),
//        @XmlElement(name = "IMPORT", type = IMPORT.class),
//        @XmlElement(name = "EXPORT", type = EXPORT.class)
    })
    private List<Object> childObjects;

    /**
     * Gets the value of the metadataObjects property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadataObjects property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadataObjects().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(scale) are allowed in the list
     * {@link MetadataDouble }
     * {@link MetadataFloat }
     * {@link MetadataInteger }
     * {@link MetadataSet }
     * {@link MetadataString }
     *
     */
    /*
    public List<X3DMetadataObject> getMetadataObjects() {
        if (metadataObjects == null) {
            metadataObjects = new ArrayList<X3DMetadataObject>();
        }
        return this.metadataObjects;
    }
*/
    /**
     * Gets the value of the childObjects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the childObjects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChildObjects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(scale) are allowed in the list
     * {@link Appearance }
     * {@link Background }
     * {@link ColorInterpolator }
     * {@link CoordinateInterpolator }
     * {@link DirectionalLight }
     * {@link Group }
     * {@link NavigationInfo }
     * {@link NormalInterpolator }
     * {@link OrientationInterpolator }
     * {@link PositionInterpolator }
     * {@link ScalarInterpolator }
     * {@link Shape }
     * {@link TimeSensor }
     * {@link Transform }
     * {@link Viewpoint }
     * {@link WorldInfo }
     * {@link Anchor }
     * {@link BooleanFilter }
     * {@link BooleanSequencer }
     * {@link BooleanToggle }
     * {@link BooleanTrigger }
     * {@link CylinderSensor }
     * {@link Inline }
     * {@link IntegerSequencer }
     * {@link IntegerTrigger }
     * {@link KeySensor }
     * {@link PlaneSensor }
     * {@link PointLight }
     * {@link ProximitySensor }
     * {@link SphereSensor }
     * {@link SpotLight }
     * {@link StringSensor }
     * {@link Switch }
     * {@link TimeTrigger }
     * {@link TouchSensor }
     * {@link AudioClip }
     * {@link Billboard }
     * {@link Collision }
     * {@link Fog }
     * {@link LoadSensor }
     * {@link LocalFog }
     * {@link LOD }
     * {@link Script }
     * {@link Sound }
     * {@link VisibilitySensor }
     * {@link CoordinateInterpolator2D }
     * {@link PositionInterpolator2D }
     * {@link StaticGroup }
     * {@link CADAssembly }
     * {@link CADLayer }
     * {@link OrthoViewpoint }
     * {@link ViewpointGroup }
     * {@link ColorDamper }
     * {@link CoordinateDamper }
     * {@link OrientationChaser }
     * {@link OrientationDamper }
     * {@link PositionChaser }
     * {@link PositionChaser2D }
     * {@link PositionDamper }
     * {@link PositionDamper2D }
     * {@link ScalarChaser }
     * {@link TexCoordDamper2D }
     * {@link TextureBackground }
     * {@link CollidableShape }
     * {@link CollisionSensor }
     * {@link RigidBodyCollection }
     * {@link EspduTransform }
     * {@link ReceiverPdu }
     * {@link SignalPdu }
     * {@link TransmitterPdu }
     * {@link DISEntityManager }
     * {@link GeoLocation }
     * {@link GeoLOD }
     * {@link GeoMetadata }
     * {@link GeoOrigin }
     * {@link GeoPositionInterpolator }
     * {@link GeoProximitySensor }
     * {@link GeoTouchSensor }
     * {@link GeoViewpoint }
     * {@link GeoTransform }
     * {@link HAnimHumanoid }
     * {@link HAnimJoint }
     * {@link HAnimSegment }
     * {@link HAnimSite }
     * {@link NurbsOrientationInterpolator }
     * {@link NurbsPositionInterpolator }
     * {@link NurbsSurfaceInterpolator }
     * {@link NurbsSet }
     * {@link ProtoInstance }
     * {@link ROUTE }
     * {@link ExternProtoDeclare }
     * {@link ProtoDeclare }
     * {@link IMPORT }
     * {@link EXPORT }
     * 
     */
    public List<Object> getChildObjects() {
        if (childObjects == null) {
            childObjects = new ArrayList<>();
        }
        return this.childObjects;
    }

}
