//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:21:15 AM EDT 
//

package org.x3d.model;

/*
 * _
 * The Open Semantic Network Analysis Platform (OSNAP)
 * _
 * Copyright (C) 2012 - 2014 Visionarium at Virginia Tech
 * _
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * _
 */

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.x3d.fields.MFFloat;
import org.x3d.fields.MFString;
import org.x3d.fields.SFBool;
import org.x3d.fields.SFFloat;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}X3DGeometryNode">
 *       &lt;sequence minOccurs="0">
 *         &lt;group ref="{}TextChildContentModel"/>
 *       &lt;/sequence>
 *       &lt;attribute name="string" type="{}MFString" />
 *       &lt;attribute name="length" type="{}MFFloat" />
 *       &lt;attribute name="maxExtent" default="0.0">
 *         &lt;simpleType>
 *           &lt;restriction base="{}SFFloat">
 *             &lt;minInclusive value="0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="solid" type="{}SFBool" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "fontStyle"
// "protoInstance"
})
@XmlRootElement(name = "Text")
public class Text extends X3DGeometryNode {

	@XmlElement(name = "FontStyle")
	protected FontStyle fontStyle;
	// @XmlElement(name = "ProtoInstance")
	// protected ProtoInstance protoInstance;
	@XmlAttribute(name = "string")
	protected MFString string;
	@XmlAttribute(name = "length")
	protected MFFloat length;
	@XmlAttribute(name = "maxExtent")
	protected SFFloat maxExtent;
	@XmlAttribute(name = "solid")
	protected SFBool solid;

	/**
	 * Gets the value of the fontStyle property.
	 * 
	 * @return possible object is {@link FontStyle }
	 * 
	 */
	public FontStyle getFontStyle() {
		return fontStyle;
	}

	/**
	 * Sets the value of the fontStyle property.
	 * 
	 * @param value
	 *            allowed object is {@link FontStyle }
	 * 
	 */
	public void setFontStyle(FontStyle value) {
		this.fontStyle = value;
	}

	/**
	 * Gets the value of the protoInstance property.
	 * 
	 * @return possible object is {@link ProtoInstance }
	 * 
	 */
	// public ProtoInstance getProtoInstance() {
	// return protoInstance;
	// }

	/**
	 * Sets the value of the protoInstance property.
	 * 
	 * @param value
	 *            allowed object is {@link ProtoInstance }
	 * 
	 */
	// public void setProtoInstance(ProtoInstance value) {
	// this.protoInstance = value;
	// }

	/**
	 * Gets the value of the string property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the string property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getString().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(scale) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public MFString getString() {
		return this.string;
	}

	public void setString(MFString string) {
		this.string = string;
	}

	/**
	 * Gets the value of the length property.
	 * 
	 * @return possible object is {@link MFFloat }
	 * 
	 */
	public MFFloat getLength() {
		return length;
	}

	/**
	 * Sets the value of the length property.
	 * 
	 * @param value
	 *            allowed object is {@link MFFloat }
	 * 
	 */
	public void setLength(MFFloat value) {
		this.length = value;
	}

	/**
	 * Gets the value of the maxExtent property.
	 * 
	 * @return possible object is {@link SFFloat }
	 * 
	 */
	public SFFloat getMaxExtent() {
		return maxExtent;
	}

	/**
	 * Sets the value of the maxExtent property.
	 * 
	 * @param value
	 *            allowed object is {@link SFFloat }
	 * 
	 */
	public void setMaxExtent(SFFloat value) {
		this.maxExtent = value;
	}

	/**
	 * Gets the value of the solid property.
	 * 
	 * @return possible object is {@link SFBool }
	 * 
	 */
	public SFBool isSolid() {
		return solid;
	}

	/**
	 * Sets the value of the solid property.
	 * 
	 * @param value
	 *            allowed object is {@link SFBool }
	 * 
	 */
	public void setSolid(SFBool value) {
		this.solid = value;
	}

}
