//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2011.06.16 at 09:21:15 AM EDT
//


package org.x3d.model;

/*
 * _
 * The Open Semantic Network Analysis Platform (OSNAP)
 * _
 * Copyright (C) 2012 - 2014 Visionarium at Virginia Tech
 * _
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * _
 */

import org.x3d.fields.BoundingBoxSize;
import org.x3d.fields.SFVec3f;


/**
 * <p>
 * Java class for X3DBoundedObject.
 * 
 * <p>
 * X3DBoundedObject indicates that bounding box values can be provided (or
 * computed) for this node and any children. Bounding box values approximate the
 * volume of a containing box in the current coordinate system. Bounding box
 * values can optionally be provided to (or calculated by) 3D browsers. Bounding
 * box values are hints that can improve performance by allowing browsers to
 * inexpensively cull geometry, thus avoiding the computational cost of trying
 * to drawing shapes when they are outside of the current view.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="X3DBoundedObject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="bboxCenter" type="{}SFVec3f" default="0 0 0" />
 *       &lt;attribute name="bboxSize" type="{}BoundingBoxSize" default="-1 -1 -1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
public interface X3DBoundedObject {


    /**
     * Gets the value of the bboxCenter property.
     * 
     * @return possible object is {@link SFVec3f }
     * 
     */
    public abstract SFVec3f getBboxCenter();

    /**
     * Sets the value of the bboxCenter property.
     * 
     * @param value
     *            allowed object is {@link SFVec3f }
     * 
     */
    public abstract void setBboxCenter(SFVec3f value);

    /**
     * Gets the value of the bboxSize property.
     * 
     * @return possible object is {@link BoundingBoxSize }
     * 
     */
    public abstract BoundingBoxSize getBboxSize();

    /**
     * Sets the value of the bboxSize property.
     * 
     * @param value
     *            allowed object is {@link BoundingBoxSize }
     * 
     */
    public abstract void setBboxSize(BoundingBoxSize value);

}
