//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2011.06.16 at 09:21:15 AM EDT
//

package org.x3d.model;


import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>
 * Java class for X3DNode complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="X3DNode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}IS" minOccurs="0"/>
 *         &lt;group ref="{}ChildContentModelCore" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}globalAttributes"/>
 *       &lt;attGroup ref="{}DEF_USE"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "X3DNode", propOrder = { "is", "metadataObject", "def", "use" })
@XmlSeeAlso({
// X3DFogObject.class,
// X3DPrototypeInstanceNode.class,
// WildcardNodeType.class,
// X3DParticlePhysicsModelNode.class,
// LayoutGroup.class,
// X3DLayerNode.class,
// LayerSet.class,
// DISEntityTypeMapping.class,
// X3DRigidJointNode.class,
// RigidBody.class,
// X3DNBodyCollisionSpaceNode.class,
// ViewpointGroup.class,
// ShaderPart.class,
// Contour2D.class,
        X3DFontStyleNode.class,
        // GeoOrigin.class,
        X3DAppearanceNode.class, X3DAppearanceChildNode.class,
        // X3DParticleEmitterNode.class,
        X3DChildNode.class,
//         X3DGeometricPropertyNode.class,
         X3DGeometryNode.class,
        X3DMetadataObject.class })
public abstract class X3DNode {

    @XmlElement(name = "IS")
    private IS                is;

    @XmlElements({
            @XmlElement(name = "MetadataDouble", type = MetadataDouble.class),
            @XmlElement(name = "MetadataFloat", type = MetadataFloat.class),
            @XmlElement(name = "MetadataInteger", type = MetadataInteger.class),
            @XmlElement(name = "MetadataSet", type = MetadataSet.class),
            @XmlElement(name = "MetadataString", type = MetadataString.class) })
    private X3DMetadataObject metadataObject;

    @XmlAttribute(name = "class")
    @XmlSchemaType(name = "NMTOKENS")
    private List<String>      clazz;

    @XmlAttribute(name = "DEF")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    private String            def;

    @XmlAttribute(name = "USE")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    private X3DNode           use;

    /**
     * Gets the value of the is property.
     * 
     * @return possible object is {@link IS }
     * 
     */
    public IS getIS() {

        return is;
    }

    /**
     * Sets the value of the is property.
     * 
     * @param value
     *            allowed object is {@link IS }
     * 
     */
    public void setIS(IS value) {

        this.is = value;
    }

    /**
     * Gets the value of the metadataObject property.
     * 
     * @return possible object is {@link MetadataDouble }
     * 
     */
    public X3DMetadataObject getMetadataObject() {

        return metadataObject;
    }

    /**
     * Sets the value of the metadataObject property.
     * 
     * @param value
     *            allowed object is {@link X3DMetadataObject }
     * 
     */
    public void setMetadataObject(X3DMetadataObject value) {

        this.metadataObject = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the clazz property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getClazz().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(scale) are allowed in the list {@link String }
     * 
     * 
     */
    public List<String> getClazz() {

        if (clazz == null) {
            clazz = new ArrayList<>();
        }
        return this.clazz;
    }

    /**
     * Gets the value of the def property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDEF() {

        return def;
    }

    /**
     * Sets the value of the def property.
     * 
     * @param value
     *            allowed object is {@link String }
     * 
     */
    public void setDEF(String value) {

        this.def = value;
    }

    /**
     * Gets the value of the use property.
     * 
     * @return possible object is {@link X3DNode }
     * 
     */
    public X3DNode getUSE() {

        return use;
    }

    /**
     * Sets the value of the use property.
     * 
     * @param value
     *            allowed object is {@link X3DNode }
     * 
     */
    public void setUSE(X3DNode value) {

        this.use = value;
    }

}
