//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:21:15 AM EDT 
//


package x3d.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for accessTypeNames.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="accessTypeNames">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="initializeOnly"/>
 *     &lt;enumeration value="inputOnly"/>
 *     &lt;enumeration value="outputOnly"/>
 *     &lt;enumeration value="inputOutput"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "accessTypeNames")
@XmlEnum
public enum AccessTypeNames {

    @XmlEnumValue("initializeOnly")
    INITIALIZE_ONLY("initializeOnly"),
    @XmlEnumValue("inputOnly")
    INPUT_ONLY("inputOnly"),
    @XmlEnumValue("outputOnly")
    OUTPUT_ONLY("outputOnly"),
    @XmlEnumValue("inputOutput")
    INPUT_OUTPUT("inputOutput");
    private final String value;

    AccessTypeNames(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AccessTypeNames fromValue(String v) {
        for (AccessTypeNames c: AccessTypeNames.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
