//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:21:15 AM EDT 
//


package x3d.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import x3d.fields.MFString;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}X3DBackgroundNode">
 *       &lt;attribute name="backUrl" type="{}MFString" />
 *       &lt;attribute name="bottomUrl" type="{}MFString" />
 *       &lt;attribute name="frontUrl" type="{}MFString" />
 *       &lt;attribute name="leftUrl" type="{}MFString" />
 *       &lt;attribute name="rightUrl" type="{}MFString" />
 *       &lt;attribute name="topUrl" type="{}MFString" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Background")
public class Background
    extends X3DBackgroundNode
{

    @XmlAttribute(name = "backUrl")
    protected MFString backUrl;
    @XmlAttribute(name = "bottomUrl")
    protected MFString bottomUrl;
    @XmlAttribute(name = "frontUrl")
    protected MFString frontUrl;
    @XmlAttribute(name = "leftUrl")
    protected MFString leftUrl;
    @XmlAttribute(name = "rightUrl")
    protected MFString rightUrl;
    @XmlAttribute(name = "topUrl")
    protected MFString topUrl;

    /**
     * Gets the value of the backUrl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the backUrl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBackUrl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(scale) are allowed in the list
     * {@link x3d.fields.SFString }
     * 
     * 
     */
    public MFString getBackUrl() {
        if (backUrl == null) {
            backUrl = new MFString();
        }
        return this.backUrl;
    }

    /**
     * Gets the value of the bottomUrl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bottomUrl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBottomUrl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(scale) are allowed in the list
     * {@link x3d.fields.SFString }
     * 
     * 
     */
    public MFString getBottomUrl() {
        if (bottomUrl == null) {
            bottomUrl = new MFString();
        }
        return this.bottomUrl;
    }

    /**
     * Gets the value of the frontUrl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the frontUrl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFrontUrl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(scale) are allowed in the list
     * {@link x3d.fields.SFString }
     * 
     * 
     */
    public MFString getFrontUrl() {
        if (frontUrl == null) {
            frontUrl = new MFString();
        }
        return this.frontUrl;
    }

    /**
     * Gets the value of the leftUrl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the leftUrl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLeftUrl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(scale) are allowed in the list
     * {@link x3d.fields.SFString }
     * 
     * 
     */
    public MFString getLeftUrl() {
        if (leftUrl == null) {
            leftUrl = new MFString();
        }
        return this.leftUrl;
    }

    /**
     * Gets the value of the rightUrl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rightUrl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRightUrl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(scale) are allowed in the list
     * {@link x3d.fields.SFString }
     * 
     * 
     */
    public MFString getRightUrl() {
        if (rightUrl == null) {
            rightUrl = new MFString();
        }
        return this.rightUrl;
    }

    /**
     * Gets the value of the topUrl property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the topUrl property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTopUrl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(scale) are allowed in the list
     * {@link x3d.fields.SFString }
     * 
     * 
     */
    public MFString getTopUrl() {
        if (topUrl == null) {
            topUrl = new MFString();
        }
        return this.topUrl;
    }

}
