//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:21:15 AM EDT 
//


package x3d.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


import x3d.fields.SFVec3f;
import x3d.fields.SFBool;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}X3DLightNode">
 *       &lt;attribute name="direction" type="{}SFVec3f" default="0 0 -1" />
 *       &lt;attribute name="global" type="{}SFBool" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "DirectionalLight")
public class DirectionalLight
    extends X3DLightNode
{

    @XmlAttribute(name = "direction")
    protected SFVec3f direction;
    @XmlAttribute(name = "global")
    protected SFBool global;

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link SFVec3f }
     *     
     */
    public SFVec3f getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFVec3f }
     *     
     */
    public void setDirection(SFVec3f value) {
        this.direction = value;
    }

    /**
     * Gets the value of the global property.
     * 
     * @return
     *     possible object is
     *     {@link SFBool }
     *     
     */
    public SFBool isGlobal() {
        return global;
    }

    /**
     * Sets the value of the global property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFBool }
     *     
     */
    public void setGlobal(SFBool value) {
        this.global = value;
    }

    public DirectionalLight() {
        this.direction = new SFVec3f ( 0.0f, 0.0f, -1.0f);
        this.global = new SFBool (false);
    }



}
