//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:21:15 AM EDT 
//


package x3d.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import x3d.fields.SFBool;
import x3d.fields.SFInt32;
import x3d.fields.SFColor;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}X3DAppearanceChildNode">
 *       &lt;attribute name="filled" type="{}SFBool" default="true" />
 *       &lt;attribute name="hatched" type="{}SFBool" default="true" />
 *       &lt;attribute name="hatchStyle" type="{}SFInt32" default="1" />
 *       &lt;attribute name="hatchColor" type="{}SFColor" default="1 1 1" />
 *       &lt;attribute name="containerField" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" default="fillProperties" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "FillProperties")
public class FillProperties
    extends X3DAppearanceChildNode
{

    @XmlAttribute(name = "filled")
    protected SFBool filled;
    @XmlAttribute(name = "hatched")
    protected SFBool hatched;
    @XmlAttribute(name = "hatchStyle")
    protected SFInt32 hatchStyle;
    @XmlAttribute(name = "hatchColor")
    protected SFColor hatchColor;
    @XmlAttribute(name = "containerField")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String containerField;

    /**
     * Gets the value of the filled property.
     * 
     * @return
     *     possible object is
     *     {@link SFBool }
     *     
     */
    public SFBool isFilled() {
        if (filled == null) {
            filled = SFBool.TRUE;
        }
            return filled;
    }

    /**
     * Sets the value of the filled property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFBool }
     *     
     */
    public void setFilled(SFBool value) {
        this.filled = value;
    }

    /**
     * Gets the value of the hatched property.
     * 
     * @return
     *     possible object is
     *     {@link SFBool }
     *     
     */
    public SFBool isHatched() {
        if (hatched == null) {
            hatched = SFBool.TRUE;
        }
            return hatched;
    }

    /**
     * Sets the value of the hatched property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFBool }
     *     
     */
    public void setHatched(SFBool value) {
        this.hatched = value;
    }

    /**
     * Gets the value of the hatchStyle property.
     * 
     * @return
     *     possible object is
     *     {@link SFInt32 }
     *     
     */
    public SFInt32 getHatchStyle() {
        if (hatchStyle == null) {
            hatchStyle = new SFInt32(1);
        }
            return hatchStyle;
    }

    /**
     * Sets the value of the hatchStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFInt32 }
     *     
     */
    public void setHatchStyle(SFInt32 value) {
        this.hatchStyle = value;
    }

    /**
     * Gets the value of the hatchColor property.
     * 
     * @return
     *     possible object is
     *     {@link SFColor }
     *     
     */
    public SFColor getHatchColor() {
        if (hatchColor == null) {
            hatchColor = new SFColor (1f, 1f, 1f);
        }
            return hatchColor;
    }

    /**
     * Sets the value of the hatchColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFColor }
     *     
     */
    public void setHatchColor(SFColor value) {
        this.hatchColor = value;
    }

    /**
     * Gets the value of the containerField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerField() {
        if (containerField == null) {
            return "fillProperties";
        } else {
            return containerField;
        }
    }

    /**
     * Sets the value of the containerField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerField(String value) {
        this.containerField = value;
    }

}
