//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2011.06.16 at 09:21:15 AM EDT
//


package x3d.model;


import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import x3d.fields.SFInt32;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}X3DChildNode">
 *       &lt;attribute name="integerKey" type="{}SFInt32" default="-1" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "IntegerTrigger")
public class IntegerTrigger
        extends X3DChildNode {

    @XmlAttribute(name = "integerKey")
    private SFInt32 integerKey;

    /**
     * Gets the value of the integerKey property.
     * 
     * @return possible object is {@link SFInt32 }
     * 
     */
    public SFInt32 getIntegerKey() {

        return integerKey;
    }

    /**
     * Sets the value of the integerKey property.
     * 
     * @param value
     *            allowed object is {@link SFInt32 }
     * 
     */
    public void setIntegerKey(SFInt32 value) {

        this.integerKey = value;
    }


    /**
     * Creates a new instance of the {@link IntegerTrigger} class.
     */
    public IntegerTrigger() {

        this.integerKey = new SFInt32(-1);
    }

}
