//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:21:15 AM EDT 
//


package x3d.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}SceneGraphStructureNodeType">
 *       &lt;sequence>
 *         &lt;element ref="{}IS" minOccurs="0"/>
 *         &lt;group ref="{}ChildContentModelCore" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}globalAttributes"/>
 *       &lt;attGroup ref="{}DEF_USE"/>
 *       &lt;attribute name="name" type="{}SFString" />
 *       &lt;attribute name="reference" type="{}SFString" />
 *       &lt;attribute name="containerField" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" default="metadata" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "metadataObjects"
})
@XmlRootElement(name = "MetadataSet")
public class MetadataSet
    extends X3DMetadataObject
{
   
    @XmlElements({
        @XmlElement(name = "MetadataDouble", type = MetadataDouble.class),
        @XmlElement(name = "MetadataFloat", type = MetadataFloat.class),
        @XmlElement(name = "MetadataInteger", type = MetadataInteger.class),
        @XmlElement(name = "MetadataSet", type = MetadataSet.class),
        @XmlElement(name = "MetadataString", type = MetadataString.class)
    })
    protected List<X3DMetadataObject> metadataObjects;




    /**
     * Gets the value of the metadataObjects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadataObjects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadataObjects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(scale) are allowed in the list
     * {@link MetadataDouble }
     * {@link MetadataFloat }
     * {@link MetadataInteger }
     * {@link MetadataSet }
     * {@link MetadataString }
     * 
     * 
     */
    public List<X3DMetadataObject> getMetadataObjects() {
        if (metadataObjects == null) {
            metadataObjects = new ArrayList<>();
        }
        return this.metadataObjects;
    }
}
