//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:21:15 AM EDT 
//


package x3d.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import x3d.fields.SFString;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}SceneGraphStructureNodeType">
 *       &lt;attribute name="name" use="required" type="{}SFString" />
 *       &lt;attribute name="content" use="required" type="{}SFString" />
 *       &lt;attribute name="http-equiv" type="{}SFString" />
 *       &lt;attribute name="language" type="{}SFString" />
 *       &lt;attribute name="languageDirectionality" type="{}metaDirectionValues" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "meta")
public class Meta
    extends SceneGraphStructureNode
{

    @XmlAttribute(name = "name", required = true)
    protected SFString name;
    @XmlAttribute(name = "content", required = true)
    protected SFString content;
    @XmlAttribute(name = "http-equiv")
    protected SFString httpEquivalent;
    @XmlAttribute(name = "lang")
    protected SFString language;
    @XmlAttribute(name = "dir")
    protected MetaDirectionValues languageDirectionality;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link SFString }
     *     
     */
    public SFString getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFString }
     *     
     */
    public void setName(SFString value) {
        this.name = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link SFString }
     *     
     */
    public SFString getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFString }
     *     
     */
    public void setContent(SFString value) {
        this.content = value;
    }

    /**
     * Gets the value of the httpEquivalent property.
     * 
     * @return
     *     possible object is
     *     {@link SFString }
     *     
     */
    public SFString getHttpEquivalent() {
        return httpEquivalent;
    }

    /**
     * Sets the value of the httpEquivalent property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFString }
     *     
     */
    public void setHttpEquivalent(SFString value) {
        this.httpEquivalent = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link SFString }
     *     
     */
    public SFString getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFString }
     *     
     */
    public void setLanguage(SFString value) {
        this.language = value;
    }

    /**
     * Gets the value of the languageDirectionality property.
     * 
     * @return
     *     possible object is
     *     {@link MetaDirectionValues }
     *     
     */
    public MetaDirectionValues getLanguageDirectionality() {
        return languageDirectionality;
    }

    /**
     * Sets the value of the languageDirectionality property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaDirectionValues }
     *     
     */
    public void setLanguageDirectionality(MetaDirectionValues value) {
        this.languageDirectionality = value;
    }

}
