//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:21:15 AM EDT 
//


package x3d.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import x3d.fields.SFBool;
import x3d.fields.SFFloat;
import x3d.fields.MFString;
import x3d.fields.MFFloat;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}X3DBindableNode">
 *       &lt;attribute name="avatarSize" type="{}MFFloat" default="0.25 1.6 0.75" />
 *       &lt;attribute name="headlight" type="{}SFBool" default="true" />
 *       &lt;attribute name="speed" type="{}SFFloat" default="1" />
 *       &lt;attribute name="type" type="{}MFString" default=""EXAMINE" "ANY"" />
 *       &lt;attribute name="transitionType" type="{}MFString" default=""ANIMATE"" />
 *       &lt;attribute name="transitionTime" type="{}MFFloat" default="1.0" />
 *       &lt;attribute name="visibilityLimit" type="{}SFFloat" default="0" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "NavigationInfo")
public class NavigationInfo
    extends X3DBindableNode
{

    @XmlAttribute(name = "avatarSize")
    protected MFFloat avatarSize;
    @XmlAttribute(name = "headlight")
    protected SFBool headlight;
    @XmlAttribute(name = "speed")
    protected SFFloat speed;
    @XmlAttribute(name = "type")
    protected MFString type;
    @XmlAttribute(name = "transitionType")
    protected MFString transitionType;
    @XmlAttribute(name = "transitionTime")
    protected MFFloat transitionTime;
    @XmlAttribute(name = "visibilityLimit")
    protected SFFloat visibilityLimit;

    /**
     * Gets the value of the avatarSize property.
     * 
     * @return
     *     possible object is
     *     {@link SFFloat }
     *     
     */
    public MFFloat getAvatarSize() {
        if (avatarSize == null) {
            avatarSize = new MFFloat();
            avatarSize.add(0.25f);
            avatarSize.add(1.6f);
            avatarSize.add(0.75f);
        }
        
        return avatarSize;
        
    }

  
    /**
     * Gets the value of the headlight property.
     * 
     * @return
     *     possible object is
     *     {@link SFBool }
     *     
     */
    public SFBool isHeadlight() {
        if (headlight == null) {
            headlight = SFBool.TRUE;
        } 
        
        return headlight;
        
    }

    /**
     * Sets the value of the headlight property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFBool }
     *     
     */
    public void setHeadlight(SFBool value) {
        this.headlight = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link SFFloat }
     *     
     */
    public SFFloat getSpeed() {
        if (speed == null) {
            speed = new SFFloat(1f);
        } 
        return speed;
        
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFFloat }
     *     
     */
    public void setSpeed(SFFloat value) {
        this.speed = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the type property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(scale) are allowed in the list
     * {@link x3d.fields.SFString }
     * 
     * 
     */
    public MFString getType() {
        if (type == null) {
            type = new MFString();
            type.add("EXAMINE");
            type.add("ANY");
        }
        return this.type;
    }

    /**
     * Gets the value of the transitionType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transitionType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransitionType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(scale) are allowed in the list
     * {@link x3d.fields.SFString }
     * 
     * 
     */
    public MFString getTransitionType() {
        if (transitionType == null) {
            transitionType = new MFString();
            transitionType.add("ANIMATE");
        }
        return this.transitionType;
    }

    /**
     * Gets the value of the transitionTime property.
     * 
     * @return
     *     possible object is
     *     {@link SFFloat }
     *     
     */
    public MFFloat getTransitionTime() {
        if (transitionTime == null) {
            transitionTime = new MFFloat();
            transitionTime.add(1f);
        } 
        return transitionTime;
        
    }


    /**
     * Gets the value of the visibilityLimit property.
     * 
     * @return
     *     possible object is
     *     {@link SFFloat }
     *     
     */
    public SFFloat getVisibilityLimit() {
        if (visibilityLimit == null) {
            visibilityLimit = new SFFloat(0f);
        } 
        return visibilityLimit;
        
    }

    /**
     * Sets the value of the visibilityLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFFloat }
     *     
     */
    public void setVisibilityLimit(SFFloat value) {
        this.visibilityLimit = value;
    }

}
