//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:21:15 AM EDT 
//


package x3d.model;

import x3d.fields.SFBool;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}X3DKeyDeviceSensorNode">
 *       &lt;attribute name="deletionAllowed" type="{}SFBool" default="true" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "StringSensor")
public class StringSensor
    extends X3DKeyDeviceSensorNode
{

    @XmlAttribute(name = "deletionAllowed")
    protected SFBool deletionAllowed;

    /**
     * Gets the value of the deletionAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public SFBool isDeletionAllowed() {
        if (deletionAllowed == null) {
            deletionAllowed = SFBool.TRUE;
        }   
        return deletionAllowed;
        
    }

    /**
     * Sets the value of the deletionAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link SFBool }
     *     
     */
    public void setDeletionAllowed(SFBool value) {
        this.deletionAllowed = value;
    }

}
