//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:21:15 AM EDT 
//

package x3d.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import x3d.fields.SFInt32;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}X3DGroupingNode">
 *       &lt;attribute name="whichChoice" type="{}SFInt32" default="-1" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Switch")
public class Switch extends X3DGroupingNode {

	@XmlAttribute(name = "whichChoice")
	protected SFInt32 whichChoice;

	/**
	 * Gets the value of the whichChoice property.
	 * 
	 * @return possible object is {@link SFInt32 }
	 * 
	 */
	public SFInt32 getWhichChoice() {
		return whichChoice;
	}

	/**
	 * Sets the value of the whichChoice property.
	 * 
	 * @param value
	 *            allowed object is {@link SFInt32 }
	 * 
	 */
	public void setWhichChoice(SFInt32 value) {
		this.whichChoice = value;
	}

	public Switch() {
		this.whichChoice = new SFInt32(-1);
	}

}
