//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:21:15 AM EDT 
//


package x3d.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import x3d.fields.SFInt32;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}SceneGraphStructureNodeType">
 *       &lt;attribute name="name" use="required" type="{}componentNames" />
 *       &lt;attribute name="level" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{}SFInt32">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="5"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "component")
public class Component
    extends SceneGraphStructureNode
{

    @XmlAttribute(name = "name", required = true)
    protected ComponentNames name;
    @XmlAttribute(name = "level", required = true)
    protected SFInt32 level;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link ComponentNames }
     *     
     */
    public ComponentNames getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComponentNames }
     *     
     */
    public void setName(ComponentNames value) {
        this.name = value;
    }

    /**
     * Gets the value of the level property.
     * 
     */
    public SFInt32 getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     */
    public void setLevel(SFInt32 value) {

        if (value.getValue() > 0 && value.getValue() < 6){
            this.level = value;
        }
         else {
            throw new IllegalArgumentException("Component level has to be between 1 and 5. Value Provided is " + value.getValue());
         }
    }

}
