//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:21:15 AM EDT 
//


package x3d.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for profileNames.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="profileNames">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Core"/>
 *     &lt;enumeration value="Interchange"/>
 *     &lt;enumeration value="CADInterchange"/>
 *     &lt;enumeration value="Interactive"/>
 *     &lt;enumeration value="Immersive"/>
 *     &lt;enumeration value="MPEG4Interactive"/>
 *     &lt;enumeration value="Full"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "profileNames")
@XmlEnum
public enum ProfileNames {

    @XmlEnumValue("Core")
    CORE("Core"),
    @XmlEnumValue("Interchange")
    INTERCHANGE("Interchange"),
    @XmlEnumValue("CADInterchange")
    CAD_INTERCHANGE("CADInterchange"),
    @XmlEnumValue("Interactive")
    INTERACTIVE("Interactive"),
    @XmlEnumValue("Immersive")
    IMMERSIVE("Immersive"),
    @XmlEnumValue("MPEG4Interactive")
    MPEG_4_INTERACTIVE("MPEG4Interactive"),
    @XmlEnumValue("Full")
    FULL("Full");
    private final String value;

    ProfileNames(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProfileNames fromValue(String v) {
        for (ProfileNames c: ProfileNames.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
