//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:21:15 AM EDT 
//


package x3d.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for X3DAppearanceChildNode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="X3DAppearanceChildNode">
 *   &lt;complexContent>
 *     &lt;extension base="{}X3DNode">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "X3DAppearanceChildNode")
@XmlSeeAlso({
//    X3DTextureTransformNode.class,
//    TextureProperties.class,
//    X3DTextureNode.class,
//    X3DEnvironmentTextureNode.class,
//    X3DShaderNode.class,
    X3DMaterialNode.class,
    LineProperties.class,
    FillProperties.class
})
public abstract class X3DAppearanceChildNode
    extends X3DNode
{


}
