//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:21:15 AM EDT 
//


package x3d.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}SceneGraphStructureNodeType">
 *       &lt;sequence>
 *         &lt;element ref="{}head" minOccurs="0"/>
 *         &lt;element ref="{}Scene"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{}x3dVersion" />
 *       &lt;attribute name="profile" use="required" type="{}profileNames" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlType(name = "", propOrder = {
    "head",
    "scene"
})
@XmlRootElement(name = "X3D")
public class X3DDocument
    extends SceneGraphStructureNode
{

    
    protected Head head;    
    protected Scene scene;    
    protected X3DVersion version;    
    protected ProfileNames profile;

    /**
     * Gets the value of the head property.
     * 
     * @return
     *     possible object is
     *     {@link Head }
     *     
     */
    @XmlElement(name = "head", required = false)
    public Head getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     * 
     * @param value
     *     allowed object is
     *     {@link Head }
     *     
     */
    public void setHead(Head value) {
        this.head = value;
    }

    /**
     * Gets the value of the scene property.
     * 
     * @return
     *     possible object is
     *     {@link Scene }
     *     
     */
    @XmlElement(name = "Scene", required = true)
    public Scene getScene() {
        return scene;
    }

    /**
     * Sets the value of the scene property.
     * 
     * @param value
     *     allowed object is
     *     {@link Scene }
     *     
     */
    public void setScene(Scene value) {
        this.scene = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @XmlAttribute(name = "version", required = true)
    public X3DVersion getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(X3DVersion value) {
        this.version = value;
    }

    /**
     * Gets the value of the profile property.
     * 
     * @return
     *     possible object is
     *     {@link ProfileNames }
     *     
     */
    @XmlAttribute(name = "profile", required = true)
    public ProfileNames getProfile() {
        return profile;
    }

    /**
     * Sets the value of the profile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProfileNames }
     *     
     */
    public void setProfile(ProfileNames value) {
        this.profile = value;
    }

}
