//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.16 at 09:21:15 AM EDT 
//


package x3d.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for metaDirectionValues.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="x3dVersion">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="3.0"/>
 *     &lt;enumeration value="3.1"/>
 *     &lt;enumeration value="3.2"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "X3DVersion")
@XmlEnum
public enum X3DVersion {

    @XmlEnumValue("3.0")
    X3D_3_0("3.0"),
    @XmlEnumValue("3.1")
    X3D_3_1("3.1"),
    @XmlEnumValue("3.2")
    X3D_3_2("3.2");

    private final String value;

    X3DVersion(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static X3DVersion fromValue(String v) {
        for (X3DVersion c: X3DVersion.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
